### ISSUE TITLE
Setup script fails for project with framework target

### ISSUE THREAD

**Issue by alijaza** [objectbox/objectbox-swift#33]
I have a single workspace with multiple nested projects. One of those projects is just a framework that is embedded in multiple other subprojects. The structure looks something like this:

```
/Root
  /Framework
  /Project1
  /Project2
  /Pods
```

When I try to run the generator from the Framework subdirectory I get no generated files:

```
../Pods/ObjectBox/setup.rb
 ObjectBox Project Setup

🔸 Looking for project files in the current directory ...
🔸 Found a single project.
🔸 Using "Root/Framework/Framework.xcodeproj"

 🔸 No changes made to project.

 💬 Please remember to use the .xcworkspace CocoaPods created from now on instead of your project.

```

When I try to run it from the root directory I see this:

```
./Pods/ObjectBox/setup.rb ./Framework Framework
 ObjectBox Project Setup

🔸 Using "./Framework"
Traceback (most recent call last):
	3: from ./Pods/ObjectBox/setup.rb:191:in `<main>'
	2: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.15.0/lib/xcodeproj/project.rb:112:in `open'
	1: from /Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.15.0/lib/xcodeproj/project.rb:210:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.15.0/lib/xcodeproj/plist.rb:17:in `read_from_path': [!] The plist file at path `/Root/Framework/project.pbxproj` doesn't exist. (Xcodeproj::Informative)
```

Is this configuration supported?

**Comment by alijaza** [comment]
Ah, stupid mistake. In case anyone else runs into the same issue, the setup command should have been `Pods/ObjectBox/setup.rb ./Framework/Framework.xcodeproj/ Framework` (From the Root directory).
